### ISSUE TITLE
Permit aws_config_regions to be a string listing a single region

### ISSUE THREAD

**Issue by bretmartin** [bretmartin/ansible-role-aws-config#4]
See the conversation in #2.

**Comment by bretmartin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Ansible role aws-{cloudtrail,config} region specification bugs](https://trello.com/c/jpkE8RQu/392-ansible-role-aws-cloudtrailconfig-region-specification-bugs)

**Comment by bretmartin** [comment]
@msaundersh3 Let me suggest a strategy for you to work through what's happening here.

Make a copy of **regions.yml** and duplicate or loop over the problematic task that starts on line 17 several times. Before each iteration of that task, set `aws_config_regions` to a test value (`ALL`, `NONE`, `us-east-1`, `['us-east-1', 'us-east-2']`, etc.). After each iteration, print the value of `_aws_config_configured_regions`, being sure to do so in a way that you can see whitespace, including newlines.

I think you recently said you think this is a YAML folding issue, but I don't think it is. (Incidentally, for that, the best explanation and reference I've found is [this StackOverflow answer](https://stackoverflow.com/a/21699210).)

What is the other key mechanism in use in this task that controls whitespace and newlines?

**Comment by bretmartin** [comment]
Oh, and by all means keep running the complete role if you'd like, but recall that if you do what I've described above, you can run just the test task list you've created instead of everything.

**Comment by msaundersh3** [comment]
@bretmartin Thank you for all the troubleshooting tips!  

I had mentally moved on from my folding theory before stepping away last week but hadn't touched any code yet.  I'll take a look at this later today.
